apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 71-master-sshd-motd
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - path: '/etc/motd'
          mode: 0444
          overwrite: true
          contents:
            source: https://raw.githubusercontent.com/mcipamo/ssh-motd/main/ssh.motd
